[build-system]
requires = ["flit_core >=3.11,<5"]
build-backend = "flit_core.buildapi"

[project]
name = "reverlor_test_masikol"
dynamic = ["version"]
authors = [
  { name="Maksim Sikolenko" },
]
description = "A program that finds inexact interspersed repeats in genomic sequences and infers if the repeats are resolved by long reads"
readme = "README.md"

requires-python = ">=3.9"
dependencies = [
  "biopython>=1.87",
  "mappy>=2.31",
  "pybedtools>=0.12.0",
  "pysam>=0.24.0",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = [
  "Bioinformatics",
  "Genome",
  "Repeats",
]
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/masikol/reverlor"
Issues = "https://github.com/masikol/reverlor/issues"

[project.scripts]
reverlor = "reverlor.reverlor:main"
reverlor_find = "reverlor.reverlor_find:main"
reverlor_verify = "reverlor.reverlor_verify:main"

[tool.flit.module]
name = "reverlor"

[tool.flit.sdist]
exclude = [
  "param_selection",
  "reverlor_venv",
  "reverlor/.pytest_cache",
]
